title: Kakau 家教網站
description: 數理家教｜教學筆記｜學習方法
lang: zh-Hant-TW
url: "https://g4kakau.github.io"
baseurl: ""

# 文章 URL 格式：/posts/文章標題/
permalink: /posts/:title/

# 分頁（之後文章多了可啟用）
# plugins:
#   - jekyll-paginate
